<a href="https://colab.research.google.com/github/kimngan-148/Nhom1.6-DHKL18A1HN-DO-AN-1/blob/De_Cuong_Do_An_1_Nhom_1_6/Nh%C3%B3m_1_6_%C4%90%E1%BB%93_%C3%A1n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PHẦN MỞ ĐẦU
https://docs.google.com/document/d/1hLiWd4nLkGxR81jf7I1VKelWlqYwxI_W/edit?usp=drive_link&ouid=101352188193095580447&rtpof=true&sd=true

### Bộ dữ liệu: :
https://www.kaggle.com/datasets/iamsouravbanerjee/gender-development-index-dataset

# ĐỀ CƯƠNG THỰC HIỆN ĐỒ ÁN 1_6

**(Dành cho sinh viên ngành Khoa học dữ liệu)**

### BỘ MÔN TOÁN & KHOA HỌC DỮ LIỆU
---
# TÊN ĐỒ ÁN
## SỬ DỤNG NGÔN NGỮ R, PYTHON ĐỂ THĂM DÒ, TRỰC QUAN, PHÂN TÍCH MỨC ĐỘ BẤT BÌNH ĐẲNG GIỚI TRONG PHÁT TRIỂN DÂN SỐ (GENDER DEVELOPMENT INDEX)

**Nhóm đăng ký đồ án:** Nhóm **1.6 – DHKL18A1HN**
---
## THÀNH VIÊN NHÓM

| STT | Họ và tên | Mã sinh viên | Điện thoại |
|:---:|---|---|---|
| 1 | Nguyễn Thị Kim Ngân | 24174600039 | 0352858148 |
| 2 | Nguyễn Thị Thu Trang | 24174600056 | 0386298906 |
| 3 | Phạm Thị Hồng Như | 24174600007 | 0985701938 |
| 4 | Trần Thu Uyên | 24174600009 | 0796496110 |
| 5 | Nguyễn Mạnh Tiến | 24174600177 | 0325738338 |

---

# TÓM TẮT NỘI DUNG ĐỒ ÁN

## 1. GIỚI THIỆU

Gender Development Index (GDI) là bộ dữ liệu phản ánh mức độ phát triển con người theo khía cạnh giới tính tại các quốc gia trên thế giới. Bộ dữ liệu được sử dụng để nghiên cứu sự khác biệt về mức độ phát triển giữa nam và nữ, đồng thời xem xét sự thay đổi của chỉ số này theo thời gian.

### Mục tiêu và tầm quan trọng của việc phân tích dữ liệu về bất bình đẳng giới trong phát triển con người

- Việc phân tích dữ liệu về bất bình đẳng giới trong phát triển con người đóng
vai trò quan trọng trong việc đánh giá mức độ phát triển và bình đẳng giữa nam và nữ tại các quốc gia và khu vực trên thế giới. Gender Development Index (GDI) là một trong những chỉ số được sử dụng để phản ánh sự khác biệt về mức độ phát triển của con người giữa hai giới thông qua các khía cạnh quan trọng như sức khỏe, giáo dục và thu nhập. Mục tiêu của việc phân tích dữ liệu GDI là cung cấp cái nhìn tổng quan và chi tiết về khoảng cách phát triển giữa nam và nữ, từ đó xác định những lĩnh vực còn tồn tại sự chênh lệch đáng kể.

- Thông qua việc phân tích dữ liệu theo thời gian, chúng ta có thể theo dõi sự thay đổi của mức độ bình đẳng giới giữa các quốc gia và khu vực. Việc nghiên cứu các chỉ số như tuổi thọ, số năm đi học, thu nhập và GDI giúp xác định những xu hướng phát triển tích cực hoặc những khoảng cách giới vẫn còn tồn tại.

- Bên cạnh đó, việc so sánh dữ liệu giữa nam và nữ còn giúp làm rõ sự khác biệt trong cơ hội tiếp cận giáo dục, điều kiện sức khỏe và khả năng tạo ra thu nhập. Những kết quả này có thể cung cấp cơ sở dữ liệu hữu ích cho việc nghiên cứu các vấn đề xã hội và phát triển con người.

---

# 2. THU THẬP DỮ LIỆU

### Nguồn dữ liệu

**Gender Development Index (GDI)**

**Link dữ liệu:**  
https://www.kaggle.com/datasets/iamsouravbanerjee/gender-development-index-dataset?utm_source=gemini

---

- Làm sạch dữ liệu và xử lý giá trị thiếu:
- Kiểm tra và xử lý các giá trị thiếu trong dữ liệu, loại bỏ các bản ghi trùng lặp hoặc dữ liệu không hợp, kiểm tra và xử lý các giá trị ngoại lai nếu có.
- Chuyển đổi định dạng dữ liệu: Chuyển đổi các biến phân loại như Country và Gender Development Index của từng năm, kiểm tra xem có bất cứ dữ liệu của năm nào không phải kiểu dữ liệu số không?. Quy chuẩn tất cả thành dạng số để thuận tiện cho việc phân tích, chuẩn hóa dữ liệu của các biến định lượng nếu cần thiết.
- Chuyển đổi dữ liệu :
  + Sử dụng thư viện tidyr để đưa dữ liệu về dạng thuận tiện cho việc phân tích và trực quan hóa dữ liệu.
  + Chuyển đổi từ Wide sang Long là bước quan trọng cho việc trực quan sau này khi dữ liệu chuyển đổi về từng năm tách biệt chứ không xen kẽ nhiều quốc gia mà tách riêng dữ liệu của từng quốc gia cùng với 32 dòng dữ liệu của 32 năm.


---

# 3. THỐNG KÊ MÔ TẢ
- Các đại lượng thống kê cơ bản: Tần suất (Frequency), Trung bình(Mean), Trung vị(Median), Phương sai(Variance) và Độ lệch chuẩn(Standard Deviation), Phân phối(Distribution).
- Phân tích phân phối dữ liệu. Để phân tích sự khác biệt giữa các yếu tố liên quan đén GDI:
- Sử dụng ước lượng tỷ lệ để xác định tỷ lệ các quốc gia thuộc từng nhóm phát triển con người và so sánh tỷ lệ giữa các nhóm.
- Sử dụng ước lượng khoảng / kiểm định trung bình để so sánh giá trị GDI trung bình giữa các nhóm phát triển con người hoặc giữa các khu vực ( các châu lục ).


---

# 4. MỐI LIÊN HỆ GIỮA CÁC BIẾN

- Biến HDI Rank (2021) và GDI (2021):
  + HDI Rank (2021) là biến Human Development Index Rank trong năm 2021: Đánh giá mức độ phát triển con người dựa trên sức khoẻ, giáo dục, thu nhập.
  + GDI (2021) là biến Gender Development Index trong năm 2021: So sánh mức độ phát triển giữa nữ và nam dựa trên sức khoẻ, giáo dục, thu nhập.
  + Mối quan hệ nghịch chiều nhau.
- Mối liên hệ giữa GDI qua - Biến HDI Rank (2021) và GDI (2021):
  + HDI Rank (2021) là biến Human Development Index - Rank trong năm 2021: Đánh giá mức độ phát triển con người dựa trên sức khoẻ, giáo dục, thu nhập.
  + GDI (2021) là biến Gender Development Index trong năm 2021: So sánh mức độ phát triển giữa nữ và nam dựa trên sức khoẻ, giáo dục, thu nhập.
  + Mối quan hệ nghịch chiềucác năm:
  + Nhìn qua chỉ số GDI tương quan với GDI năm 2021 ta thấy GDI 2020: 0.999; GDI 2019: 0.994; GDI 2018: 0.987; GDI 2017: 0.978, GDI: 2015: 0.977,…. . Cho thấy các quốc gia có GDI cao/thấp trong những năm gần đây thường vẫn có xu hướng giữ vị trí tương đối tương tự so với các quốc gia khác. Đồng thời, tương quan giảm dần khi khoảng cách thời gian tăng.
  + GDI có tính ổn định theo thời gian nhưng vẫn có thể có sự thay đổi về dài hạn.
- Mối liên hệ giữa GDI và Human Development Groups:
  + Human Development Groups là biến phân loại chia các quốc gia thành các nhóm theo các mức độ: Very High  /  High  /  Medium  /  Low.
  + GDI có sự khác biệt giữa các nhóm Human Development Groups. Các quốc gia thuộc nhóm có mức độ phát triển con người cao hơn có xu hướng GDI cao hơn, trong khi nhóm có mức độ phát triển con người thấp hơn có xu hướng có GDI thấp hơn. Điều này cho thấy có mối liên hệ giữa các mức độ phát triển con người và GDI trong bộ dữ liệu
- Biểu đồ boxplot:
  + Boxplot phù hợp với mối quan hệ này khi giúp ta nhìn ra được Median GDI của từng nhóm, khoảng phân bố GDI, độ phân tán, Outlier hay Mức độ chồng lấn giữa các nhóm


---

# 5. TRỰC QUAN HÓA DỮ LIỆU

* Mục tiêu: Khai phá khoảng cách phát triển giữa nam và nữ trên các chỉ số y tế, giáo dục và thu nhập qua các năm.
## 5.1. Trực quan hoá số lượng
- Mục đích là phân tích số lượng quốc gia và số lượng quan sát trong tập dữ liệu theo các nhóm phân loại có sẵn, bao gồm: châu lục, bán cầu, nhóm phát triển con người, khu vực đang phát triển của UNDP và theo từng năm.
- Sử dụng biểu đồ cột( Bar Plot), biểu đồ tròn( Pie Chart)
## 5.2. Trực quan hoá phân phối
- Mục đích là phân tích sự phân bố của chỉ số Phát triển Giới (GDI) trong tập dữ liệu qua các năm từ 1990 đến 2021.
- Các biến định lượng được phân tích:
  + Chỉ số phát triển giới GDI từ năm 1990 đến 2021.
  + Xếp hạng HDI năm 2021 khi cần phân tích bổ sung
- Sử dụng Histogram, Density Plot, Box Plot

## 5.3. Trực quan hóa nhiều phân phối đồng thời
- Mục đích là so sánh phân phối của chỉ số GDI giữa nhiều năm vầ các quốc gia có trong tập dữ liệu.
- Các nhóm được phân tích:
  + Sử dụng Box Plot, Histogram, Violin Plot
  + Các năm từ 1990 đến 2021
  + Các châu lục
  + Các nhóm phát triển con người
  + Các khu vực đang phát triển theo UNDP
- Sử dụng Box Plot, Histogram, Violin Plot
## 5.4. Trực quan hoá tỷ lệ
- Phân tích tỷ lệ và cơ cấu các quốc gia theo những nhóm phân loại có sẵn trong dữ liệu theo các đặc điểm:
  + Châu lục
  + Bán cầu
  + Nhóm phát triển con người
  + Khu vực đang phát triển theo UNDP
  + Có dữ liệu hoặc không có dữ liệu GDI trong từng năm
- Sử dụng biểu đồ cột(Bar chart), biểu đồ cột nhóm( Grouped Bar Chart), Biểu đồ tròn(Pie Chart)
## 5.5. Trực quan hoá nhóm tỷ lệ lồng nhau
- Mục đích là phân tích sự phân bố của các nhóm quốc gia khi kết hợp từ hai đặc điểm phân loại trở lên.
- Các mối quan hệ được phân tích:
  + Châu lục và nhóm phát triển con người
  + Châu lục và bán cầu
  + Châu lục và khu vực UNDP
  + Nhóm phát triển con người và khu vực UNDP
  + Nhóm phát triển con người và mức GDI được phân nhóm
  + Khu vực UNDP và mức GDI được phân nhóm
- Sử dụng biểu đồ chồng( Stacked Bar Chart), biểu đồ cột nhóm( Grouped Bar Chart),Heatmap
## 5.6. Trực quan hoá mối quan hệ giữa 2 hoặc nhiều biến định lượng
- Mục đích là phân tích mối liên hệ giữa chỉ số GDI và các biến dạng lượng khác có trong tập dữ liệu, đồng thời xem xét sự thay đổi của GDI theo thời gian.
- Các biến phân tích:
  + Chỉ số GDI từ năm 1990 đến 2021
  + Xếp hạng HDI năm 2021
- Sử dụng Scatter Plot, Line Chart, Heatmap


---

# 6. Chủ đề nâng cao
- Nhóm lựa chọn chủ đề: phân loại các quốc gia dựa trên bình đẳng giới trong nhân khẩu học bằng thuật toán K-Means.
- Sử dụng các biến cho phân cụm GDI.
- Trực quan hoá kết quả phân cụm và phân tích đặc điểm của từng nhóm quốc gia.
- So sánh các cụm theo GDI và nhóm vùng UNDP để xác định đặc điểm và sự phân bổ của các nhóm quốc gia.


---

# 7. Bảng phân công công việc

## BẢNG PHÂN CÔNG CÔNG VIỆC

| STT | Nội dung công việc | Kết quả đạt được | Thời gian | Người thực hiện |
|:---:|:---|:---|:---:|:---|
| 1 | Thu thập dữ liệu | Tải dữ liệu từ nguồn Kaggle, tạo ra danh sách nguồn dữ liệu thành bộ dữ liệu thô ban đầu. | 22/09/2026 | Cả nhóm |
| 2 | Làm sạch và tiền xử lý dữ liệu | - Kiểm tra dữ liệu.<br>- Xử lý dữ liệu trùng lặp.<br>- Xử lý giá trị thiếu.<br>- Chuẩn hóa tên cột.- Kiểm tra dữ liệu.<br>- Kiểm tra dữ liệu sau khi làm sạch.<br>- Tiền xử lý dữ liệu.<br> | 13/10/2026 | Nguyễn Thị Thu Trang<br>*(Hỗ trợ: Phạm Thị Hồng Như, Trần Thu Uyên)* |
| 3 | Thống kê mô tả | - Các đại lượng thống kê cơ bản: Tần suất (Frequency), Trung bình (Mean), Trung vị (Median), Phương sai (Variance), Độ lệch chuẩn (Standard Deviation), Phân phối (Distribution).<br>- Phân tích phân phối dữ liệu:<br>  + Ước lượng tỷ lệ xác định tỷ lệ các quốc gia thuộc từng nhóm phát triển con người.<br>  + Ước lượng khoảng / kiểm định trung bình so sánh GDI trung bình giữa các nhóm hoặc khu vực.<br>  | 14/10/2026 - 15/10/2026 | Nguyễn Thị Kim Ngân<br>*(Hỗ trợ: )* |
| 4 | Tìm hiểu mối liên hệ giữa các biến | - Mối liên hệ giữa biến HDI Rank (2021) và GDI (2021).<br>- Mối liên hệ giữa GDI qua các năm (xu hướng giữ vị trí tương đối và giảm độ tương quan khi khoảng cách thời gian tăng).<br>- Mối liên hệ giữa GDI và Human Development Groups.<br>- Vẽ biểu đồ Boxplot. | 05/10/2026 - 08/10/2026 | Nguyễn Thị Kim Ngân<br>*(Hỗ trợ: )* |
| 5 | Trực quan hoá số lượng | - Biểu đồ cột (Bar Plot) thể hiện số lượng quốc gia theo châu lục, nhóm phát triển con người, khu vực UNDP, số lượng quan sát GDI theo năm.<br>- Biểu đồ tròn (Pie Chart) thể hiện tỷ trọng quốc gia theo châu lục/nhóm phát triển con người. | 09/10/2026 - 14/10/2026 | Nguyễn Thị Kim Ngân<br>*(Hỗ trợ: )* |
| 6 | Trực quan hoá phân phối | - Histogram thể hiện phân bố giá trị GDI.<br>- Density Plot quan sát hình dạng và mức độ tập trung.<br>- Boxplot thể hiện trung vị, khoảng phân bố và giá trị bất thường của GDI. | 19/10/2026 - 22/10/2026 | Trần Thu Uyên<br>*(Hỗ trợ: )* |
| 7 | Trực quan hóa nhiều phân phối đồng thời | - Boxplot so sánh phân phối GDI giữa các nhóm phát triển con người, châu lục, khu vực UNDP.<br>- Histogram / Density Plot so sánh phân phối GDI giữa các năm tiêu biểu.<br>- Violin Plot thể hiện hình dạng phân phối và mật độ GDI. | 25/10/2026 - 30/10/2026 | Trần Thu Uyên<br>*(Hỗ trợ: )* |
| 8 | Trực quan hoá tỷ lệ | - Biểu đồ cột (Bar Chart) so sánh số lượng và tỷ lệ quốc gia.<br>- Biểu đồ cột nhóm (Grouped Bar Chart) so sánh cơ cấu nhóm giữa các châu lục/năm.<br>- Biểu đồ tròn (Pie Chart) thể hiện tỷ lệ quốc gia. | 02/11/2026 - 04/11/2026 | Nguyễn Mạnh Tiến<br>*(Hỗ trợ: )* |
| 9 | Trực quan hoá nhóm tỷ lệ lồng nhau | - Biểu đồ cột chồng (Stacked Bar Chart) thể hiện cơ cấu nhóm theo nhóm phân loại thứ hai.<br>- Biểu đồ cột nhóm (Grouped Bar Chart) so sánh trực tiếp số lượng.<br>- Heatmap thể hiện số lượng quốc gia giữa hai nhóm phân loại. | 07/11/2026 - 10/11/2026 | Nguyễn Thị Thu Trang<br>*(Hỗ trợ: )* |
| 10 | Trực quan hoá mối liên hệ giữa 2 hoặc nhiều biến định lượng | - Scatter Plot biểu diễn mối quan hệ giữa GDI và HDI Rank 2021, xu hướng GDI theo thời gian.<br>- Line Chart thể hiện sự thay đổi GDI qua các năm.<br>- Heatmap tương quan giữa các giá trị GDI của các năm khác nhau. | 15/11/2026 - 17/11/2026 | Phạm Thị Hồng Như<br>*(Hỗ trợ: )* |
| 11 | Chủ đề nâng cao | Trực quan hoá kết quả phân cụm (phân loại các quốc gia dựa trên bình đẳng giới trong nhân khẩu học bằng thuật toán K-Means) và phân tích đặc điểm từng nhóm quốc gia. | 18/11/2026 - 19/11/2026 | Phạm Thị Hồng Như<br>*(Hỗ trợ: )* |
| 12 | Viết báo cáo | Hoàn thiện báo cáo trực quan hóa dữ liệu đồ án 1. | 20/11/2026 | Cả nhóm |

#**CHƯƠNG 1:** TỔNG QUAN VÀ THU THẬP, TÍCH HỢP DỮ LIỆU

### 1.1. Thu thập dữ liệu từ kaggle

In [2]:
!pip install -q kagglehub

In [3]:
import kagglehub
import pandas as pd
import os

# Tải bộ dữ liệu từ Kaggle
path = kagglehub.dataset_download(
    "iamsouravbanerjee/gender-development-index-dataset"
)

# Đọc trực tiếp file CSV
df = pd.read_csv(
    os.path.join(
        path,
        "Gender Development Index.csv"
    )
)

# Hiển thị 5 dòng đầu
display(df.head())

Downloading to /root/.cache/kagglehub/datasets/iamsouravbanerjee/gender-development-index-dataset/1.archive...

100%|██████████| 10.9k/10.9k [00:00<00:00, 17.0MB/s]

Extracting files...

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Gender Development Index (1990),Gender Development Index (1991),Gender Development Index (1992),...,Gender Development Index (2012),Gender Development Index (2013),Gender Development Index (2014),Gender Development Index (2015),Gender Development Index (2016),Gender Development Index (2017),Gender Development Index (2018),Gender Development Index (2019),Gender Development Index (2020),Gender Development Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,0.588,0.586,...,0.649,0.659,0.630,0.673,0.682,0.703,0.710,0.712,0.689,0.681
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,NaN,NaN,NaN,...,0.848,0.866,0.884,0.893,0.900,0.900,0.903,0.902,0.904,0.903
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,0.922,0.921,0.932,...,0.974,0.968,0.968,0.984,0.988,0.991,0.997,1.002,1.006,1.007
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,0.961,0.958,0.957,...,0.919,0.920,0.921,0.922,0.921,0.945,0.948,0.955,0.952,0.953

#**CHƯƠNG 2:**  LÀM SẠCH VÀ TIỀN XỬ LÝ DỮ LIỆU

### 2.1. Kiểm tra dữ liệu

In [4]:
# Kiểm tra thông tin các cột
df.info()

# Kiểm tra kích thước dữ liệu
print("Kích thước dữ liệu:", df.shape)

# Kiểm tra số lượng giá trị thiếu ở từng cột
print("\nSố lượng giá trị thiếu:")
print(df.isnull().sum())

# Kiểm tra số dòng bị trùng lặp
print("\nSố dòng trùng lặp:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ISO3                             195 non-null    object
 1   Country                          195 non-null    object
 2   Continent                        195 non-null    object
 3   Hemisphere                       195 non-null    object
 4   Human Development Groups         191 non-null    object
 5   UNDP Developing Regions          151 non-null    object
 6   HDI Rank (2021)                  191 non-null    float64
 7   Gender Development Index (1990)  111 non-null    float64
 8   Gender Development Index (1991)  111 non-null    float64
 9   Gender Development Index (1992)  111 non-null    float64
 10  Gender Development Index (1993)  112 non-null    float64
 11  Gender Development Index (1994)  112 non-null    float64
 12  Gender Development Index (1995)  130 non-null    float64
 13  Gender Development Index (1996)  130 non-null    float64
 14  Gender Development Index (1997)  130 non-null    float64
 15  Gender Development Index (1998)  131 non-null    float64
 16  Gender Development Index (1999)  137 non-null    float64
 17  Gender Development Index (2000)  154 non-null    float64
 18  Gender Development Index (2001)  155 non-null    float64
 19  Gender Development Index (2002)  157 non-null    float64
 20  Gender Development Index (2003)  160 non-null    float64
 21  Gender Development Index (2004)  162 non-null    float64
 22  Gender Development Index (2005)  166 non-null    float64
 23  Gender Development Index (2006)  167 non-null    float64
 24  Gender Development Index (2007)  167 non-null    float64
 25  Gender Development Index (2008)  167 non-null    float64
 26  Gender Development Index (2009)  167 non-null    float64
 27  Gender Development Index (2010)  171 non-null    float64
 28  Gender Development Index (2011)  171 non-null    float64
 29  Gender Development Index (2012)  171 non-null    float64
 30  Gender Development Index (2013)  171 non-null    float64
 31  Gender Development Index (2014)  171 non-null    float64
 32  Gender Development Index (2015)  171 non-null    float64
 33  Gender Development Index (2016)  171 non-null    float64
 34  Gender Development Index (2017)  172 non-null    float64
 35  Gender Development Index (2018)  172 non-null    float64
 36  Gender Development Index (2019)  172 non-null    float64
 37  Gender Development Index (2020)  172 non-null    float64
 38  Gender Development Index (2021)  172 non-null    float64
dtypes: float64(33), object(6)
memory usage: 59.5+ KB
Kích thước dữ liệu: (195, 39)

Số lượng giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Số dòng trùng lặp: 0

### 2.2. Xử lý dữ liệu trùng lặp

In [5]:
# Xóa các dòng bị trùng lặp
df = df.drop_duplicates()

# Kiểm tra lại số dòng trùng lặp
print("Số dòng trùng lặp sau khi xử lý:", df.duplicated().sum())

Số dòng trùng lặp sau khi xử lý: 0

### 2.3. Xử lý giá trị thiếu

In [6]:
# Kiểm tra và xử lý giá trị thiếu
print("Số lượng giá trị thiếu:")
print(df.isnull().sum())

print("\nTỷ lệ giá trị thiếu (%):")
print((df.isnull().mean() * 100).round(2))

print("\nKích thước dữ liệu:", df.shape)

Số lượng giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Tỷ lệ giá trị thiếu (%):
ISO3                                0.00
Country                             0.00
Continent                           0.00
Hemisphere                          0.00
Human Development Groups            2.05
UNDP Developing Regions            22.56
HDI Rank (2021)                     2.05
Gender Development Index (1990)    43.08
Gender Development Index (1991)    43.08
Gender Development Index (1992)    43.08
Gender Development Index (1993)    42.56
Gender Development Index (1994)    42.56
Gender Development Index (1995)    33.33
Gender Development Index (1996)    33.33
Gender Development Index (1997)    33.33
Gender Development Index (1998)    32.82
Gender Development Index (1999)    29.74
Gender Development Index (2000)    21.03
Gender Development Index (2001)    20.51
Gender Development Index (2002)    19.49
Gender Development Index (2003)    17.95
Gender Development Index (2004)    16.92
Gender Development Index (2005)    14.87
Gender Development Index (2006)    14.36
Gender Development Index (2007)    14.36
Gender Development Index (2008)    14.36
Gender Development Index (2009)    14.36
Gender Development Index (2010)    12.31
Gender Development Index (2011)    12.31
Gender Development Index (2012)    12.31
Gender Development Index (2013)    12.31
Gender Development Index (2014)    12.31
Gender Development Index (2015)    12.31
Gender Development Index (2016)    12.31
Gender Development Index (2017)    11.79
Gender Development Index (2018)    11.79
Gender Development Index (2019)    11.79
Gender Development Index (2020)    11.79
Gender Development Index (2021)    11.79
dtype: float64

Kích thước dữ liệu: (195, 39)

### 2.4. Chuẩn hóa tên cột

In [7]:
# Xóa khoảng trắng ở đầu và cuối tên cột
df.columns = df.columns.str.strip()

# Hiển thị tên các cột sau khi chuẩn hóa
print("Tên các cột:")
print(df.columns.tolist())

Tên các cột:
['ISO3', 'Country', 'Continent', 'Hemisphere', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)', 'Gender Development Index (1990)', 'Gender Development Index (1991)', 'Gender Development Index (1992)', 'Gender Development Index (1993)', 'Gender Development Index (1994)', 'Gender Development Index (1995)', 'Gender Development Index (1996)', 'Gender Development Index (1997)', 'Gender Development Index (1998)', 'Gender Development Index (1999)', 'Gender Development Index (2000)', 'Gender Development Index (2001)', 'Gender Development Index (2002)', 'Gender Development Index (2003)', 'Gender Development Index (2004)', 'Gender Development Index (2005)', 'Gender Development Index (2006)', 'Gender Development Index (2007)', 'Gender Development Index (2008)', 'Gender Development Index (2009)', 'Gender Development Index (2010)', 'Gender Development Index (2011)', 'Gender Development Index (2012)', 'Gender Development Index (2013)', 'Gender Development Index (2014)', 'Gender Development Index (2015)', 'Gender Development Index (2016)', 'Gender Development Index (2017)', 'Gender Development Index (2018)', 'Gender Development Index (2019)', 'Gender Development Index (2020)', 'Gender Development Index (2021)']

### 2.5. Kiểm tra dữ liệu

In [8]:
# Kiểm tra kiểu dữ liệu của các cột
print(df.dtypes)

ISO3                                object
Country                             object
Continent                           object
Hemisphere                          object
Human Development Groups            object
UNDP Developing Regions             object
HDI Rank (2021)                    float64
Gender Development Index (1990)    float64
Gender Development Index (1991)    float64
Gender Development Index (1992)    float64
Gender Development Index (1993)    float64
Gender Development Index (1994)    float64
Gender Development Index (1995)    float64
Gender Development Index (1996)    float64
Gender Development Index (1997)    float64
Gender Development Index (1998)    float64
Gender Development Index (1999)    float64
Gender Development Index (2000)    float64
Gender Development Index (2001)    float64
Gender Development Index (2002)    float64
Gender Development Index (2003)    float64
Gender Development Index (2004)    float64
Gender Development Index (2005)    float64
Gender Development Index (2006)    float64
Gender Development Index (2007)    float64
Gender Development Index (2008)    float64
Gender Development Index (2009)    float64
Gender Development Index (2010)    float64
Gender Development Index (2011)    float64
Gender Development Index (2012)    float64
Gender Development Index (2013)    float64
Gender Development Index (2014)    float64
Gender Development Index (2015)    float64
Gender Development Index (2016)    float64
Gender Development Index (2017)    float64
Gender Development Index (2018)    float64
Gender Development Index (2019)    float64
Gender Development Index (2020)    float64
Gender Development Index (2021)    float64
dtype: object

### 2.6. Kiểm tra dữ liệu sau khi làm sạch

In [9]:
# Hiển thị dữ liệu sau khi làm sạch
display(df.head())

# Kiểm tra thông tin dữ liệu
df.info()

# Kiểm tra giá trị thiếu
print("\nGiá trị thiếu:")
print(df.isnull().sum())

# Kiểm tra dữ liệu trùng lặp
print("\nSố dòng trùng lặp:", df.duplicated().sum())

# Kiểm tra kích thước dữ liệu
print("\nKích thước dữ liệu:", df.shape)

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Gender Development Index (1990),Gender Development Index (1991),Gender Development Index (1992),...,Gender Development Index (2012),Gender Development Index (2013),Gender Development Index (2014),Gender Development Index (2015),Gender Development Index (2016),Gender Development Index (2017),Gender Development Index (2018),Gender Development Index (2019),Gender Development Index (2020),Gender Development Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,0.588,0.586,...,0.649,0.659,0.630,0.673,0.682,0.703,0.710,0.712,0.689,0.681
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,NaN,NaN,NaN,...,0.848,0.866,0.884,0.893,0.900,0.900,0.903,0.902,0.904,0.903
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,0.922,0.921,0.932,...,0.974,0.968,0.968,0.984,0.988,0.991,0.997,1.002,1.006,1.007
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,0.961,0.958,0.957,...,0.919,0.920,0.921,0.922,0.921,0.945,0.948,0.955,0.952,0.953

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ISO3                             195 non-null    object
 1   Country                          195 non-null    object
 2   Continent                        195 non-null    object
 3   Hemisphere                       195 non-null    object
 4   Human Development Groups         191 non-null    object
 5   UNDP Developing Regions          151 non-null    object
 6   HDI Rank (2021)                  191 non-null    float64
 7   Gender Development Index (1990)  111 non-null    float64
 8   Gender Development Index (1991)  111 non-null    float64
 9   Gender Development Index (1992)  111 non-null    float64
 10  Gender Development Index (1993)  112 non-null    float64
 11  Gender Development Index (1994)  112 non-null    float64
 12  Gender Development Index (1995)  130 non-null    float64
 13  Gender Development Index (1996)  130 non-null    float64
 14  Gender Development Index (1997)  130 non-null    float64
 15  Gender Development Index (1998)  131 non-null    float64
 16  Gender Development Index (1999)  137 non-null    float64
 17  Gender Development Index (2000)  154 non-null    float64
 18  Gender Development Index (2001)  155 non-null    float64
 19  Gender Development Index (2002)  157 non-null    float64
 20  Gender Development Index (2003)  160 non-null    float64
 21  Gender Development Index (2004)  162 non-null    float64
 22  Gender Development Index (2005)  166 non-null    float64
 23  Gender Development Index (2006)  167 non-null    float64
 24  Gender Development Index (2007)  167 non-null    float64
 25  Gender Development Index (2008)  167 non-null    float64
 26  Gender Development Index (2009)  167 non-null    float64
 27  Gender Development Index (2010)  171 non-null    float64
 28  Gender Development Index (2011)  171 non-null    float64
 29  Gender Development Index (2012)  171 non-null    float64
 30  Gender Development Index (2013)  171 non-null    float64
 31  Gender Development Index (2014)  171 non-null    float64
 32  Gender Development Index (2015)  171 non-null    float64
 33  Gender Development Index (2016)  171 non-null    float64
 34  Gender Development Index (2017)  172 non-null    float64
 35  Gender Development Index (2018)  172 non-null    float64
 36  Gender Development Index (2019)  172 non-null    float64
 37  Gender Development Index (2020)  172 non-null    float64
 38  Gender Development Index (2021)  172 non-null    float64
dtypes: float64(33), object(6)
memory usage: 59.5+ KB

Giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Số dòng trùng lặp: 0

Kích thước dữ liệu: (195, 39)

### 2.7. Tiền xử lý dữ liệu

#### 2.7.1. Kiểm tra và xử lý tên cột, dữ liệu dạng chữ

In [10]:
# Chuẩn hóa tên cột
df.columns = df.columns.str.strip()

# Xác định các cột dạng chữ
text_columns = df.select_dtypes(
    include=["object"]
).columns.tolist()

# Loại bỏ khoảng trắng thừa ở đầu và cuối giá trị
for col in text_columns:
    df[col] = df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

# Kiểm tra kết quả
display(df.head())

print("Tên cột sau khi chuẩn hóa:")
print(df.columns.tolist())

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Gender Development Index (1990),Gender Development Index (1991),Gender Development Index (1992),...,Gender Development Index (2012),Gender Development Index (2013),Gender Development Index (2014),Gender Development Index (2015),Gender Development Index (2016),Gender Development Index (2017),Gender Development Index (2018),Gender Development Index (2019),Gender Development Index (2020),Gender Development Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,0.588,0.586,...,0.649,0.659,0.630,0.673,0.682,0.703,0.710,0.712,0.689,0.681
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,NaN,NaN,NaN,...,0.848,0.866,0.884,0.893,0.900,0.900,0.903,0.902,0.904,0.903
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,0.922,0.921,0.932,...,0.974,0.968,0.968,0.984,0.988,0.991,0.997,1.002,1.006,1.007
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,0.961,0.958,0.957,...,0.919,0.920,0.921,0.922,0.921,0.945,0.948,0.955,0.952,0.953

Tên cột sau khi chuẩn hóa:
['ISO3', 'Country', 'Continent', 'Hemisphere', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)', 'Gender Development Index (1990)', 'Gender Development Index (1991)', 'Gender Development Index (1992)', 'Gender Development Index (1993)', 'Gender Development Index (1994)', 'Gender Development Index (1995)', 'Gender Development Index (1996)', 'Gender Development Index (1997)', 'Gender Development Index (1998)', 'Gender Development Index (1999)', 'Gender Development Index (2000)', 'Gender Development Index (2001)', 'Gender Development Index (2002)', 'Gender Development Index (2003)', 'Gender Development Index (2004)', 'Gender Development Index (2005)', 'Gender Development Index (2006)', 'Gender Development Index (2007)', 'Gender Development Index (2008)', 'Gender Development Index (2009)', 'Gender Development Index (2010)', 'Gender Development Index (2011)', 'Gender Development Index (2012)', 'Gender Development Index (2013)', 'Gender Development Index (2014)', 'Gender Development Index (2015)', 'Gender Development Index (2016)', 'Gender Development Index (2017)', 'Gender Development Index (2018)', 'Gender Development Index (2019)', 'Gender Development Index (2020)', 'Gender Development Index (2021)']

#### 2.7.2. Chuyển đổi từ Wide sang Long

In [27]:
# Lấy danh sách các cột GDI theo năm
gdi_cols = [col for col in df.columns if col.startswith('Gender Development Index')]

# Trích xuất năm từ tên cột
year_mapping = {col: int(col.replace('Gender Development Index (', '').replace(')', '')) for col in gdi_cols}

# Chuyển đổi Wide sang Long bằng pd.melt
df_long = df.melt(
    id_vars=['ISO3', 'Country', 'Continent', 'Hemisphere', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)'],
    value_vars=gdi_cols,
    var_name='GDI_Year_Col',
    value_name='GDI'
)

# Tạo cột Year kiểu số nguyên
df_long['Year'] = df_long['GDI_Year_Col'].map(year_mapping)
df_long.drop(columns=['GDI_Year_Col'], inplace=True)

# Sắp xếp dữ liệu theo Country và Year
df_long = df_long.sort_values(by=['Country', 'Year']).reset_index(drop=True)

print("Kích thước bảng Wide ban đầu:", df.shape)
print("Kích thước bảng Long sau chuyển đổi:", df_long.shape)
display(df_long.head(10))

Kích thước bảng Wide ban đầu: (195, 39)
Kích thước bảng Long sau chuyển đổi: (6240, 9)

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),GDI,Year
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,1990
1,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.588,1991
2,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.586,1992
3,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.548,1993
4,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.524,1994
5,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.543,1995
6,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.544,1996
7,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.536,1997
8,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.534,1998
9,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.523,1999

#### 2.7.3. Lưu dữ liệu sau tiền xử lí

In [12]:
import os
import pandas as pd
import kagglehub

# Đảm bảo dữ liệu đã được tải và gán vào biến df nếu chưa tồn tại trong session
try:
    df
except NameError:
    print("Biến 'df' chưa tồn tại. Đang tải lại dữ liệu từ Kaggle...")
    path = kagglehub.dataset_download("iamsouravbanerjee/gender-development-index-dataset")
    df = pd.read_csv(os.path.join(path, "Gender Development Index.csv"))
    df.columns = df.columns.str.strip()
    text_columns = df.select_dtypes(include=["object"]).columns.tolist()
    for col in text_columns:
        df[col] = df[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Lưu file
df.to_csv(
    "GDI_sau_tien_xu_ly.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Đã lưu file GDI_sau_tien_xu_ly.csv thành công!")

Đã lưu file GDI_sau_tien_xu_ly.csv thành công!

#**CHƯƠNG 3:** THỐNG KÊ MÔ TẢ

### 3.1. Đại lượng thống kê cơ bản của GDI (2021) và HDI Rank (2021)

In [22]:
# Bảng thống kê đại lượng cơ bản
cols_to_stat = ['Gender Development Index (2021)', 'HDI Rank (2021)']
stats_df = df[cols_to_stat].describe().T

# Tính toán bổ sung Phương sai (Variance) và Trung vị (Median)
stats_df['variance'] = df[cols_to_stat].var()
stats_df['median'] = df[cols_to_stat].median()

# Sắp xếp lại thứ tự cột
stats_df = stats_df[['count', 'mean', 'median', 'std', 'variance', 'min', '25%', '50%', '75%', 'max']]
print("CÁC ĐẠI LƯỢNG THỐNG KÊ CƠ BẢN (NĂM 2021)")
display(stats_df.round(4))

CÁC ĐẠI LƯỢNG THỐNG KÊ CƠ BẢN (NĂM 2021)

,count,mean,median,std,variance,min,25%,50%,75%,max
Gender Development Index (2021),172.0,0.9473,0.967,0.0659,0.0043,0.496,0.92,0.967,0.989,1.034
HDI Rank (2021),191.0,95.8115,96.000,55.3073,3058.9011,1.000,48.50,96.000,143.500,191.000

### 3.2. Ước lượng tỷ lệ phân bố theo nhóm phát triển con người

In [23]:
# Tần suất và Tỷ lệ phần trăm của Human Development Groups
hd_counts = df['Human Development Groups'].value_counts(dropna=False)
hd_props = (df['Human Development Groups'].value_counts(normalize=True, dropna=False) * 100).round(2)

prop_summary = pd.DataFrame({
    'Số lượng quốc gia': hd_counts,
    'Tỷ lệ (%)': hd_props
})

print("BẢNG PHÂN BỐ CÁC NHÓM PHÁT TRIỂN CON NGUỜI (HUMAN DEVELOPMENT GROUPS)")
display(prop_summary)

BẢNG PHÂN BỐ CÁC NHÓM PHÁT TRIỂN CON NGUỜI (HUMAN DEVELOPMENT GROUPS)

                          Số lượng quốc gia  Tỷ lệ (%)
Human Development Groups
Very High                                66      33.85
High                                     49      25.13
Medium                                   44      22.56
Low                                      32      16.41
NaN                                       4       2.05

### 3.3. Ước lượng khoảng và Kiểm định trung bình GDI giữa các nhóm

In [24]:
import scipy.stats as stats

# Chuẩn bị dữ liệu sạch cho ANOVA
df_anova = df.dropna(subset=['Gender Development Index (2021)', 'Human Development Groups'])

# Gom nhóm GDI 2021 theo từng Human Development Group
group_data = [group['Gender Development Index (2021)'].values for name, group in df_anova.groupby('Human Development Groups')]

# Thực hiện kiểm định ANOVA một nhân tố (One-way ANOVA)
f_stat, p_val = stats.f_oneway(*group_data)

print("KIỂM ĐỊNH SO SÁNH GDI TRUNG BÌNH GIỮA CÁC NHÓM PHÁT TRIỂN CON NGƯỜI (2021)")
print(f"Giá trị F-statistic: {f_stat:.4f}")
print(f"Giá trị p-value: {p_val:.4e}")

if p_val < 0.05:
    print("Kết luận: Có sự khác biệt có ý nghĩa thống kê về chỉ số GDI 2021 giữa các nhóm phát triển con người (p < 0.05).")
else:
    print("Kết luận: Không đủ bằng chứng cho thấy sự khác biệt có ý nghĩa thống kê.")

KIỂM ĐỊNH SO SÁNH GDI TRUNG BÌNH GIỮA CÁC NHÓM PHÁT TRIỂN CON NGƯỜI (2021)
Giá trị F-statistic: 36.1367
Giá trị p-value: 4.4943e-18
Kết luận: Có sự khác biệt có ý nghĩa thống kê về chỉ số GDI 2021 giữa các nhóm phát triển con người (p < 0.05).

#**CHƯƠNG 4:** MỐI LIÊN HỆ GIỮA CÁC BIẾN

### 4.1. Mối liên hệ giữa HDI Rank (2021) và GDI (2021)

In [18]:
# Tính hệ số tương quan Pearson giữa HDI Rank và GDI 2021
corr_hdi_gdi = df['HDI Rank (2021)'].corr(df['Gender Development Index (2021)'])

print(f"Hệ số tương quan Pearson giữa HDI Rank (2021) và GDI (2021): {corr_hdi_gdi:.4f}")
print("Nhận xét: Mối quan hệ nghịch chiều rõ rệt. Thứ hạng HDI càng cao (con số thứ hạng lớn), giá trị GDI càng có xu hướng giảm.")

Hệ số tương quan Pearson giữa HDI Rank (2021) và GDI (2021): -0.5941
Nhận xét: Mối quan hệ nghịch chiều rõ rệt. Thứ hạng HDI càng cao (con số thứ hạng lớn), giá trị GDI càng có xu hướng giảm.

### 4.2. Mối liên hệ tương quan của GDI qua các năm

In [25]:
# Ma trận tương quan giữa các cột GDI từ năm 1990 đến 2021
corr_matrix = df[gdi_cols].corr()

# Lấy hệ số tương quan của tất cả các năm so với năm 2021
corr_with_2021 = corr_matrix['Gender Development Index (2021)'].sort_values(ascending=False)

print("TƯƠNG QUAN CHỈ SỐ GDI CÁC NĂM SO VỚI GDI NĂM 202")
print(corr_with_2021.head(10).round(4))
print("\nCác năm xa nhất (1990 - 1994):")
print(corr_with_2021.tail(5).round(4))

TƯƠNG QUAN CHỈ SỐ GDI CÁC NĂM SO VỚI GDI NĂM 202
Gender Development Index (2021)    1.0000
Gender Development Index (2020)    0.9992
Gender Development Index (2019)    0.9935
Gender Development Index (2018)    0.9865
Gender Development Index (2016)    0.9827
Gender Development Index (2017)    0.9784
Gender Development Index (2015)    0.9773
Gender Development Index (2014)    0.9610
Gender Development Index (2013)    0.9540
Gender Development Index (2012)    0.9412
Name: Gender Development Index (2021), dtype: float64

Các năm xa nhất (1990 - 1994):
Gender Development Index (1994)    0.8737
Gender Development Index (1993)    0.8679
Gender Development Index (1992)    0.8564
Gender Development Index (1991)    0.8507
Gender Development Index (1990)    0.8434
Name: Gender Development Index (2021), dtype: float64

### 4.3. Mối liên hệ giữa GDI và Human Development Groups

In [26]:
# Bảng chỉ số GDI 2021 theo từng nhóm Human Development Groups
gdi_by_hd_group = df.groupby('Human Development Groups')['Gender Development Index (2021)'].agg(
    Số_quốc_gia='count',
    GDI_Trung_bình='mean',
    GDI_Trung_vị='median',
    Độ_lệch_chuẩn='std',
    Min='min',
    Max='max'
).reset_index()

print("MỐI LIÊN HỆ GIỮA GDI (2021) VÀ CÁC NHÓM PHÁT TRIỂN CON NGƯỜI")
display(gdi_by_hd_group.round(4))

MỐI LIÊN HỆ GIỮA GDI (2021) VÀ CÁC NHÓM PHÁT TRIỂN CON NGƯỜI

,Human Development Groups,Số_quốc_gia,GDI_Trung_bình,GDI_Trung_vị,Độ_lệch_chuẩn,Min,Max
0,High,43,0.9622,0.9700,0.0432,0.880,1.034
1,Low,30,0.8690,0.8825,0.0941,0.496,0.985
2,Medium,37,0.9305,0.9410,0.0469,0.803,1.004
3,Very High,62,0.9848,0.9870,0.0246,0.900,1.030

#**CHƯƠNG 5:** TRỰC QUAN HÓA DỮ LIỆU

In [21]:
import matplotlib.pyplot as plt
import seaborn as sns

# Trực quan hóa dữ liệu chung
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['font.sans-serif'] = 'DejaVu Sans'
plt.rcParams['axes.edgecolor'] = '#cccccc'

### 5.1. Trực quan hóa số lượng

### 5.2. Trực quan hóa phân phối

### 5.3. Trực quan hóa nhiều phân phối đồng thời

### 5.4. Trực quan hóa tỷ lệ

### 5.5. Trực quan hóa nhóm tỷ lệ lồng nhau

### 5.6. Trực quan hóa mối quan hệ giữa 2 hoặc nhiều biến định lượng

#**CHƯƠNG 6:** Chủ đề nâng cao