<a href="https://colab.research.google.com/github/kimngan-148/Nhom1.6-DHKL18A1HN-DO-AN-1/blob/De_Cuong_Do_An_1_Nhom_1_6/Nh%C3%B3m_1_6_%C4%90%E1%BB%93_%C3%A1n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Đề cương đồ án 1
https://docs.google.com/document/d/1hLiWd4nLkGxR81jf7I1VKelWlqYwxI_W/edit?usp=drive_link&ouid=101352188193095580447&rtpof=true&sd=true

### Bộ dữ liệu: :
https://www.kaggle.com/datasets/iamsouravbanerjee/gender-development-index-dataset

# KHOA KHOA HỌC ỨNG DỤNG

## ĐỀ CƯƠNG THỰC HIỆN ĐỒ ÁN 1

**(Dành cho sinh viên ngành Khoa học dữ liệu)**

### BỘ MÔN TOÁN & KHOA HỌC DỮ LIỆU
---
# TÊN ĐỒ ÁN
## SỬ DỤNG NGÔN NGỮ R, PYTHON ĐỂ THĂM DÒ, TRỰC QUAN, PHÂN TÍCH MỨC ĐỘ BẤT BÌNH ĐẲNG GIỚI TRONG PHÁT TRIỂN DÂN SỐ (GENDER DEVELOPMENT INDEX)

**Nhóm đăng ký đồ án:** Nhóm **1.6 – DHKL18A1HN**
---
## THÀNH VIÊN NHÓM

| STT | Họ và tên | Mã sinh viên | Điện thoại |
|:---:|---|---|---|
| 1 | Nguyễn Thị Kim Ngân | 24174600039 | 0352858148 |
| 2 | Nguyễn Thị Thu Trang | 24174600056 | 0386298906 |
| 3 | Phạm Thị Hồng Như | 24174600007 | 0985701938 |
| 4 | Trần Thu Uyên | 24174600009 | 0796496110 |
| 5 | Nguyễn Mạnh Tiến | 24174600177 | 0325738338 |

---

# TÓM TẮT NỘI DUNG ĐỒ ÁN

## 1. GIỚI THIỆU

Gender Development Index (GDI) là bộ dữ liệu phản ánh mức độ phát triển con người theo khía cạnh giới tính tại các quốc gia trên thế giới. Bộ dữ liệu được sử dụng để nghiên cứu sự khác biệt về mức độ phát triển giữa nam và nữ, đồng thời xem xét sự thay đổi của chỉ số này theo thời gian.

### Mục tiêu và tầm quan trọng của việc phân tích dữ liệu về bất bình đẳng giới trong phát triển con người

Việc phân tích dữ liệu về bất bình đẳng giới trong phát triển con người đóng
vai trò quan trọng trong việc đánh giá mức độ phát triển và bình đẳng giữa nam và nữ tại các quốc gia và khu vực trên thế giới.

Gender Development Index (GDI) là một trong những chỉ số được sử dụng để phản ánh sự khác biệt về mức độ phát triển của con người giữa hai giới thông qua các khía cạnh quan trọng như sức khỏe, giáo dục và thu nhập.

Mục tiêu của việc phân tích dữ liệu GDI là cung cấp cái nhìn tổng quan và chi tiết về khoảng cách phát triển giữa nam và nữ, từ đó xác định những lĩnh vực còn tồn tại sự chênh lệch đáng kể.

Thông qua việc phân tích dữ liệu theo thời gian, chúng ta có thể theo dõi sự thay đổi của mức độ bình đẳng giới giữa các quốc gia và khu vực.

Việc nghiên cứu các chỉ số như tuổi thọ, số năm đi học, thu nhập và GDI giúp xác định những xu hướng phát triển tích cực hoặc những khoảng cách giới vẫn còn tồn tại.

Bên cạnh đó, việc so sánh dữ liệu giữa nam và nữ còn giúp làm rõ sự khác biệt trong cơ hội tiếp cận giáo dục, điều kiện sức khỏe và khả năng tạo ra thu nhập.

Những kết quả này có thể cung cấp cơ sở dữ liệu hữu ích cho việc nghiên cứu các vấn đề xã hội và phát triển con người.

---

# 2. THU THẬP DỮ LIỆU

### Nguồn dữ liệu

**Gender Development Index (GDI)**

**Link dữ liệu:**  
https://www.kaggle.com/datasets/iamsouravbanerjee/gender-development-index-dataset?utm_source=gemini

---

## 2.1. Làm sạch dữ liệu và xử lý giá trị thiếu

- Kiểm tra và xử lý các giá trị thiếu trong dữ liệu.
- Loại bỏ các bản ghi trùng lặp hoặc dữ liệu không hợp.
- Kiểm tra và xử lý các giá trị ngoại lai nếu có.

### Chuyển đổi định dạng dữ liệu

- Chuyển đổi các biến phân loại như `Country` và `Gender Development Index` của từng năm.
- Kiểm tra xem có bất cứ dữ liệu của năm nào không phải kiểu dữ liệu số không.
- Quy chuẩn tất cả thành dạng số để thuận tiện cho việc phân tích.
- Chuẩn hóa dữ liệu của các biến định lượng nếu cần thiết.

---

## 2.2. Chuyển đổi dữ liệu

- Sử dụng thư viện `tidyr` để đưa dữ liệu về dạng thuận tiện cho việc phân tích và trực quan hóa dữ liệu.
- Chuyển đổi từ **Wide sang Long** là bước quan trọng cho việc trực quan sau này.
- Dữ liệu được chuyển đổi về từng năm tách biệt, không xen kẽ nhiều quốc gia.
- Tách riêng dữ liệu của từng quốc gia cùng với **32 dòng dữ liệu của 32 năm**.

---

# 3. Thống kê mô tả
- Các đại lượng thống kê cơ bản: Tần suất (Frequency), Trung bình(Mean), Trung vị(Median), Phương sai(Variance) và Độ lệch chuẩn(Standard Deviation), Phân phối(Distribution).
- Phân tích phân phối dữ liệu. Để phân tích sự khác biệt giữa các yếu tố liên quan đén GDI:
- Sử dụng ước lượng tỷ lệ để xác định tỷ lệ các quốc gia thuộc từng nhóm phát triển con người và so sánh tỷ lệ giữa các nhóm.
- Sử dụng ước lượng khoảng / kiểm định trung bình để so sánh giá trị GDI trung bình giữa các nhóm phát triển con người hoặc giữa các khu vực ( các châu lục ).
- Sử dụng hồi quy tuyến tính để phân tích mối quan hệ GDI và HDI Rank (2021), đồng thời đánh giá khả năng giải thích của biến HDI Rank đối với GDI.

---
# 4. Chủ đề nâng cao
-Trong phần nâng cao, nhóm sẽ xây dựng mô hình **phân tích và dự đoán xu hướng chỉ số Phát triển Giới (GDI) theo thời gian** dựa trên dữ liệu GDI của các quốc gia trong giai đoạn từ năm 1990 đến năm 2021

-Nhóm sẽ sử dụng **Linear Regression** để phân tích mối quan hệ giữa thời gian và giá trị GDI, từ đó xác định xu hướng thay đổi của chỉ số GDI qua các năm

-Quy trình thực hiện gồm:
- Tính giá trị GDI trung bình theo từng năm
- Xây dựng mô hình Linear Regression với năm là biến đầu vào và GDI trung bình là biến mục tiêu
- Chia dữ liệu thành tập huấn luyện và tập kiểm tra
- Sử dụng mô hình để dự đoán xu hướng GDI

-Mô hình sẽ được đánh giá thông qua các chỉ số:Mean Absolute Error(MAE), Mean Squared Error(MSE), Root Mean Squared Error(RMSE), R-squared(R^2)

-Kết quả dự đoán sẽ được trực quan hóa bằng biểu đồ đường, trong đó thể hiện **GDI thực tế và GDI dự đoán** theo thời gian

-Thông qua mô hình, nhóm có thể quan sát xu hướng thay đổi của GDI trong giai đoạn nghiên cứu và đánh giá khả năng sử dụng dữ liệu trong quá khứ để dự đoán xu hướng GDI trong tương lai

# Thu thập dữ liệu từ kaggle

In [ ]:
!pip install -q kagglehub

In [ ]:
import kagglehub
import pandas as pd
import os

# Tải bộ dữ liệu từ Kaggle
path = kagglehub.dataset_download(
    "iamsouravbanerjee/gender-development-index-dataset"
)

# Đọc trực tiếp file CSV
df = pd.read_csv(
    os.path.join(
        path,
        "Gender Development Index.csv"
    )
)

# Hiển thị 5 dòng đầu
display(df.head())

Using Colab cache for faster access to the 'gender-development-index-dataset' dataset.

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Gender Development Index (1990),Gender Development Index (1991),Gender Development Index (1992),...,Gender Development Index (2012),Gender Development Index (2013),Gender Development Index (2014),Gender Development Index (2015),Gender Development Index (2016),Gender Development Index (2017),Gender Development Index (2018),Gender Development Index (2019),Gender Development Index (2020),Gender Development Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,0.588,0.586,...,0.649,0.659,0.630,0.673,0.682,0.703,0.710,0.712,0.689,0.681
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,NaN,NaN,NaN,...,0.848,0.866,0.884,0.893,0.900,0.900,0.903,0.902,0.904,0.903
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,0.922,0.921,0.932,...,0.974,0.968,0.968,0.984,0.988,0.991,0.997,1.002,1.006,1.007
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,0.961,0.958,0.957,...,0.919,0.920,0.921,0.922,0.921,0.945,0.948,0.955,0.952,0.953

# Làm sạch dữ liệu

### Kiểm tra dữ liệu

In [ ]:
# Kiểm tra thông tin các cột
df.info()

# Kiểm tra kích thước dữ liệu
print("Kích thước dữ liệu:", df.shape)

# Kiểm tra số lượng giá trị thiếu ở từng cột
print("\nSố lượng giá trị thiếu:")
print(df.isnull().sum())

# Kiểm tra số dòng bị trùng lặp
print("\nSố dòng trùng lặp:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ISO3                             195 non-null    object
 1   Country                          195 non-null    object
 2   Continent                        195 non-null    object
 3   Hemisphere                       195 non-null    object
 4   Human Development Groups         191 non-null    object
 5   UNDP Developing Regions          151 non-null    object
 6   HDI Rank (2021)                  191 non-null    float64
 7   Gender Development Index (1990)  111 non-null    float64
 8   Gender Development Index (1991)  111 non-null    float64
 9   Gender Development Index (1992)  111 non-null    float64
 10  Gender Development Index (1993)  112 non-null    float64
 11  Gender Development Index (1994)  112 non-null    float64
 12  Gender Development Index (1995)  130 non-null    float64
 13  Gender Development Index (1996)  130 non-null    float64
 14  Gender Development Index (1997)  130 non-null    float64
 15  Gender Development Index (1998)  131 non-null    float64
 16  Gender Development Index (1999)  137 non-null    float64
 17  Gender Development Index (2000)  154 non-null    float64
 18  Gender Development Index (2001)  155 non-null    float64
 19  Gender Development Index (2002)  157 non-null    float64
 20  Gender Development Index (2003)  160 non-null    float64
 21  Gender Development Index (2004)  162 non-null    float64
 22  Gender Development Index (2005)  166 non-null    float64
 23  Gender Development Index (2006)  167 non-null    float64
 24  Gender Development Index (2007)  167 non-null    float64
 25  Gender Development Index (2008)  167 non-null    float64
 26  Gender Development Index (2009)  167 non-null    float64
 27  Gender Development Index (2010)  171 non-null    float64
 28  Gender Development Index (2011)  171 non-null    float64
 29  Gender Development Index (2012)  171 non-null    float64
 30  Gender Development Index (2013)  171 non-null    float64
 31  Gender Development Index (2014)  171 non-null    float64
 32  Gender Development Index (2015)  171 non-null    float64
 33  Gender Development Index (2016)  171 non-null    float64
 34  Gender Development Index (2017)  172 non-null    float64
 35  Gender Development Index (2018)  172 non-null    float64
 36  Gender Development Index (2019)  172 non-null    float64
 37  Gender Development Index (2020)  172 non-null    float64
 38  Gender Development Index (2021)  172 non-null    float64
dtypes: float64(33), object(6)
memory usage: 59.5+ KB
Kích thước dữ liệu: (195, 39)

Số lượng giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Số dòng trùng lặp: 0

### Xử lý dữ liệu trùng lặp

In [ ]:
# Xóa các dòng bị trùng lặp
df = df.drop_duplicates()

# Kiểm tra lại số dòng trùng lặp
print("Số dòng trùng lặp sau khi xử lý:", df.duplicated().sum())

Số dòng trùng lặp sau khi xử lý: 0

### Xử lý giá trị thiếu

In [ ]:
# Kiểm tra và xử lý giá trị thiếu
print("Số lượng giá trị thiếu:")
print(df.isnull().sum())

print("\nTỷ lệ giá trị thiếu (%):")
print((df.isnull().mean() * 100).round(2))

print("\nKích thước dữ liệu:", df.shape)

Số lượng giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Tỷ lệ giá trị thiếu (%):
ISO3                                0.00
Country                             0.00
Continent                           0.00
Hemisphere                          0.00
Human Development Groups            2.05
UNDP Developing Regions            22.56
HDI Rank (2021)                     2.05
Gender Development Index (1990)    43.08
Gender Development Index (1991)    43.08
Gender Development Index (1992)    43.08
Gender Development Index (1993)    42.56
Gender Development Index (1994)    42.56
Gender Development Index (1995)    33.33
Gender Development Index (1996)    33.33
Gender Development Index (1997)    33.33
Gender Development Index (1998)    32.82
Gender Development Index (1999)    29.74
Gender Development Index (2000)    21.03
Gender Development Index (2001)    20.51
Gender Development Index (2002)    19.49
Gender Development Index (2003)    17.95
Gender Development Index (2004)    16.92
Gender Development Index (2005)    14.87
Gender Development Index (2006)    14.36
Gender Development Index (2007)    14.36
Gender Development Index (2008)    14.36
Gender Development Index (2009)    14.36
Gender Development Index (2010)    12.31
Gender Development Index (2011)    12.31
Gender Development Index (2012)    12.31
Gender Development Index (2013)    12.31
Gender Development Index (2014)    12.31
Gender Development Index (2015)    12.31
Gender Development Index (2016)    12.31
Gender Development Index (2017)    11.79
Gender Development Index (2018)    11.79
Gender Development Index (2019)    11.79
Gender Development Index (2020)    11.79
Gender Development Index (2021)    11.79
dtype: float64

Kích thước dữ liệu: (195, 39)

### Chuẩn hóa tên cột

In [ ]:
# Xóa khoảng trắng ở đầu và cuối tên cột
df.columns = df.columns.str.strip()

# Hiển thị tên các cột sau khi chuẩn hóa
print("Tên các cột:")
print(df.columns.tolist())

Tên các cột:
['ISO3', 'Country', 'Continent', 'Hemisphere', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)', 'Gender Development Index (1990)', 'Gender Development Index (1991)', 'Gender Development Index (1992)', 'Gender Development Index (1993)', 'Gender Development Index (1994)', 'Gender Development Index (1995)', 'Gender Development Index (1996)', 'Gender Development Index (1997)', 'Gender Development Index (1998)', 'Gender Development Index (1999)', 'Gender Development Index (2000)', 'Gender Development Index (2001)', 'Gender Development Index (2002)', 'Gender Development Index (2003)', 'Gender Development Index (2004)', 'Gender Development Index (2005)', 'Gender Development Index (2006)', 'Gender Development Index (2007)', 'Gender Development Index (2008)', 'Gender Development Index (2009)', 'Gender Development Index (2010)', 'Gender Development Index (2011)', 'Gender Development Index (2012)', 'Gender Development Index (2013)', 'Gender Development Index (2014)', 'Gender Development Index (2015)', 'Gender Development Index (2016)', 'Gender Development Index (2017)', 'Gender Development Index (2018)', 'Gender Development Index (2019)', 'Gender Development Index (2020)', 'Gender Development Index (2021)']

### Kiểm tra dữ liệu sau khi làm sạch

In [ ]:
# Hiển thị dữ liệu sau khi làm sạch
display(df.head())

# Kiểm tra thông tin dữ liệu
df.info()

# Kiểm tra giá trị thiếu
print("\nGiá trị thiếu:")
print(df.isnull().sum())

# Kiểm tra dữ liệu trùng lặp
print("\nSố dòng trùng lặp:", df.duplicated().sum())

# Kiểm tra kích thước dữ liệu
print("\nKích thước dữ liệu:", df.shape)

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Gender Development Index (1990),Gender Development Index (1991),Gender Development Index (1992),...,Gender Development Index (2012),Gender Development Index (2013),Gender Development Index (2014),Gender Development Index (2015),Gender Development Index (2016),Gender Development Index (2017),Gender Development Index (2018),Gender Development Index (2019),Gender Development Index (2020),Gender Development Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,0.595,0.588,0.586,...,0.649,0.659,0.630,0.673,0.682,0.703,0.710,0.712,0.689,0.681
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,NaN,NaN,NaN,...,0.848,0.866,0.884,0.893,0.900,0.900,0.903,0.902,0.904,0.903
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,0.922,0.921,0.932,...,0.974,0.968,0.968,0.984,0.988,0.991,0.997,1.002,1.006,1.007
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,0.961,0.958,0.957,...,0.919,0.920,0.921,0.922,0.921,0.945,0.948,0.955,0.952,0.953

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ISO3                             195 non-null    object
 1   Country                          195 non-null    object
 2   Continent                        195 non-null    object
 3   Hemisphere                       195 non-null    object
 4   Human Development Groups         191 non-null    object
 5   UNDP Developing Regions          151 non-null    object
 6   HDI Rank (2021)                  191 non-null    float64
 7   Gender Development Index (1990)  111 non-null    float64
 8   Gender Development Index (1991)  111 non-null    float64
 9   Gender Development Index (1992)  111 non-null    float64
 10  Gender Development Index (1993)  112 non-null    float64
 11  Gender Development Index (1994)  112 non-null    float64
 12  Gender Development Index (1995)  130 non-null    float64
 13  Gender Development Index (1996)  130 non-null    float64
 14  Gender Development Index (1997)  130 non-null    float64
 15  Gender Development Index (1998)  131 non-null    float64
 16  Gender Development Index (1999)  137 non-null    float64
 17  Gender Development Index (2000)  154 non-null    float64
 18  Gender Development Index (2001)  155 non-null    float64
 19  Gender Development Index (2002)  157 non-null    float64
 20  Gender Development Index (2003)  160 non-null    float64
 21  Gender Development Index (2004)  162 non-null    float64
 22  Gender Development Index (2005)  166 non-null    float64
 23  Gender Development Index (2006)  167 non-null    float64
 24  Gender Development Index (2007)  167 non-null    float64
 25  Gender Development Index (2008)  167 non-null    float64
 26  Gender Development Index (2009)  167 non-null    float64
 27  Gender Development Index (2010)  171 non-null    float64
 28  Gender Development Index (2011)  171 non-null    float64
 29  Gender Development Index (2012)  171 non-null    float64
 30  Gender Development Index (2013)  171 non-null    float64
 31  Gender Development Index (2014)  171 non-null    float64
 32  Gender Development Index (2015)  171 non-null    float64
 33  Gender Development Index (2016)  171 non-null    float64
 34  Gender Development Index (2017)  172 non-null    float64
 35  Gender Development Index (2018)  172 non-null    float64
 36  Gender Development Index (2019)  172 non-null    float64
 37  Gender Development Index (2020)  172 non-null    float64
 38  Gender Development Index (2021)  172 non-null    float64
dtypes: float64(33), object(6)
memory usage: 59.5+ KB

Giá trị thiếu:
ISO3                                0
Country                             0
Continent                           0
Hemisphere                          0
Human Development Groups            4
UNDP Developing Regions            44
HDI Rank (2021)                     4
Gender Development Index (1990)    84
Gender Development Index (1991)    84
Gender Development Index (1992)    84
Gender Development Index (1993)    83
Gender Development Index (1994)    83
Gender Development Index (1995)    65
Gender Development Index (1996)    65
Gender Development Index (1997)    65
Gender Development Index (1998)    64
Gender Development Index (1999)    58
Gender Development Index (2000)    41
Gender Development Index (2001)    40
Gender Development Index (2002)    38
Gender Development Index (2003)    35
Gender Development Index (2004)    33
Gender Development Index (2005)    29
Gender Development Index (2006)    28
Gender Development Index (2007)    28
Gender Development Index (2008)    28
Gender Development Index (2009)    28
Gender Development Index (2010)    24
Gender Development Index (2011)    24
Gender Development Index (2012)    24
Gender Development Index (2013)    24
Gender Development Index (2014)    24
Gender Development Index (2015)    24
Gender Development Index (2016)    24
Gender Development Index (2017)    23
Gender Development Index (2018)    23
Gender Development Index (2019)    23
Gender Development Index (2020)    23
Gender Development Index (2021)    23
dtype: int64

Số dòng trùng lặp: 0

Kích thước dữ liệu: (195, 39)

### Lưu dữ liệu đã làm sạch

In [ ]:
# Lưu dữ liệu đã làm sạch thành file CSV
df.to_csv("gender_development_index_cleaned.csv", index=False)

## Chuyển đổi dữ liệu sang dạng Tidy Data & Tạo biến mới

In [ ]:
import pandas as pd
import numpy as np

# 1. Chuyển dữ liệu từ dạng Rộng (Wide) sang dạng Dài (Long - Tidy Data)
id_cols = ['ISO3', 'Country', 'Continent', 'Hemisphere', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)']
value_cols = [c for c in df.columns if 'Gender Development Index (' in c]

df_long = pd.melt(df, id_vars=id_cols, value_vars=value_cols, var_name='Year_Raw', value_name='GDI')
df_long['Year'] = df_long['Year_Raw'].str.extract(r'(\d{4})').astype(int)
df_long = df_long.drop(columns=['Year_Raw'])

# 2. Mã hóa giá trị khuyết biến định tính
df_long['UNDP Developing Regions'] = df_long['UNDP Developing Regions'].fillna('Developed/Other')
df_long['Human Development Groups'] = df_long['Human Development Groups'].fillna('Unknown')

# 3. Nội suy tuyến tính chuỗi thời gian GDI theo từng quốc gia
df_long = df_long.sort_values(['ISO3', 'Year']).reset_index(drop=True)
df_long['GDI_Clean'] = df_long.groupby('ISO3')['GDI'].transform(
    lambda g: g.interpolate(method='linear', limit=2, limit_direction='both')
)

# 4. Tạo biến mới: Tốc độ tăng trưởng (% GDI Growth)
df_long['GDI_Growth_%'] = df_long.groupby('ISO3')['GDI_Clean'].pct_change() * 100
df_clean = df_long.dropna(subset=['GDI_Clean']).reset_index(drop=True)

# 5. Lưu file Tidy Data chuẩn
df_clean.to_csv("GDI_Cleaned_Tidy.csv", index=False)
print(f"✅ Đã tạo dữ liệu Tidy Data thành công! Kích thước: {df_clean.shape[0]} dòng, {df_clean.shape[1]} cột.")
display(df_clean.head())

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(3, 2, figsize=(16, 18))

# 3.1. Line Chart: Xu hướng GDI 1990 - 2021
sns.lineplot(data=df_clean, x='Year', y='GDI_Clean', hue='Human Development Groups', estimator='mean', errorbar=None, ax=axes[0, 0], linewidth=2.5)
axes[0, 0].set_title('3.1. Xu hướng GDI Trung bình Toàn cầu (1990–2021)', fontweight='bold', fontsize=12)

# 3.2. Histogram + Density: Phân phối & Outliers năm 2021
sns.histplot(data=df_clean[df_clean['Year'] == 2021], x='GDI_Clean', kde=True, color='teal', ax=axes[0, 1])
axes[0, 1].set_title('3.2. Phân phối Chỉ số GDI năm 2021', fontweight='bold', fontsize=12)

# 3.3. Boxplot: So sánh Phân phối GDI theo Vùng UNDP (Phát hiện Outliers)
sns.boxplot(data=df_clean[df_clean['Year'] == 2021], x='UNDP Developing Regions', y='GDI_Clean', palette='Set2', ax=axes[1, 0])
axes[1, 0].set_title('3.3. So sánh Phân phối GDI 2021 theo Phân vùng UNDP', fontweight='bold', fontsize=12)
axes[1, 0].tick_params(axis='x', rotation=20)

# 3.4. Bar Chart: GDI Trung bình theo Châu lục năm 2021
gdi_cont = df_clean[df_clean['Year'] == 2021].groupby('Continent')['GDI_Clean'].mean().reset_index()
sns.barplot(data=gdi_cont, x='Continent', y='GDI_Clean', palette='Blues_d', ax=axes[1, 1])
axes[1, 1].set_title('3.4. Chỉ số GDI Trung bình năm 2021 theo Châu lục', fontweight='bold', fontsize=12)

# 3.5. Grouped Bar Chart: So sánh GDI Châu lục mốc 1990 vs 2021
sns.barplot(data=df_clean[df_clean['Year'].isin([1990, 2021])], x='Continent', y='GDI_Clean', hue='Year', palette='magma', ax=axes[2, 0])
axes[2, 0].set_title('3.5. So sánh GDI giữa các Châu lục (1990 vs 2021)', fontweight='bold', fontsize=12)

# 3.6. Scatter Plot: Mối liên hệ GDI vs HDI Rank 2021
sns.scatterplot(data=df_clean[df_clean['Year'] == 2021], x='HDI Rank (2021)', y='GDI_Clean', hue='Human Development Groups', ax=axes[2, 1], alpha=0.8)
axes[2, 1].set_title('3.6. Mối liên hệ giữa HDI Rank và GDI (2021)', fontweight='bold', fontsize=12)

plt.tight_layout()
plt.show()

# Phân tích Thống kê Mô tả & Kiểm định Giả thuyết